### PR TITLE
feat: provide `PatchMergeType::Apply` support

### PR DESCRIPTION
**Pull request by EstebanBorai**
Provides a content type support for `Apply` as suggested here https://kubernetes.io/docs/reference/using-api/server-side-apply/#serialization to provide Server-Side Apply.

### CODE REVIEW

**Comment by EstebanBorai** [comment]
Clippy issues addressed here: https://github.com/infinyon/k8-api/pull/309

**Review by nacardin — COMMENTED** [review]
So if you pass `PatchMergeType::Apply` to `patch_status` it will always fail?

**Review by nacardin — COMMENTED** [review]
Nice! Just need to bump crate versions

**Review by nacardin — APPROVED** [review]
LGTM

**Pull request merged**
